### ISSUE TITLE
User image height not styled right!

### ISSUE THREAD

**Issue by driptamine** [kenny-hibino/hackafy#1]
Hey, @kenny-hibino it'll fix style,
if you add 
```css
  height: 100%;
```

 to: ```hackafy/src/styles/GalleryItem.css ```
```css
.GalleryItem-header__avatar-img {
  display: inline-block;
  width: 100%;
  border-radius: 50%;
}
```
